export const HTTP_STATUS = {
    OK: 200,
    CREATED: 201,
    BAD_REQUEST: 400,
    UNAUTHORIZED: 401,
    FORBIDDEN: 403,
    NOT_FOUND: 404,
    INTERNAL_SERVER_ERROR: 500,
};

export const AUTH_MESSAGES = {
    REGISTER_SUCCESS: "User registered successfully!",
    REGISTER_ERROR: "Failed to register user.",
    USER_ALREADY_REGISTERED_ERROR: "User is already registered. Kindly Login!",
    USER_NOT_FOUND_ERROR: "User not registered",
    LOGIN_SUCCESS: "User logged in successfully.",
    WRONG_PASSWORD: "Wrong password",
    INVALID_CREDENTIALS: "Invalid Email or Password.",
    SERVER_ERROR: "An unexpected error occurred while processing your request.",
};

export const BOOK_MESSAGES = {
    FETCH_SUCCESS: "Books fetched successfully.",
    FETCH_ERROR: "Failed to fetch books.",
    UNAUTHORIZED: "Unauthorized",
    BOOK_NOT_FOUND: "Book not found",
    FAVORITE_REMOVED: "Book removed from favorites",
    FAVORITE_ADDED: "Book added to favorites",
    TOGGLE_ERROR: "Failed to toggle favorite",
    FAVORITE_FETCH_ERROR: "Failed to fetch favorites",
    ADD_SUCCESS: "Book added successfully",
    ADD_ERROR: "Failed to add book",
    UPDATE_SUCCESS: "Book updated successfully",
    UPDATE_ERROR: "Failed to update book",
    COPIES_ERROR: "Cannot reduce total copies below currently issued copies",
    DELETE_SUCCESS: "Book deleted successfully",
    DELETE_ERROR: "Failed to delete book",
};

export const BORROW_MESSAGES = {
    MISSING_ID: "Missing user or book ID",
    FORBIDDEN: "Admins and Librarians cannot borrow books.",
    NO_COPIES: "No copies available",
    LIMIT_REACHED: "You have reached the maximum limit of 4 active borrowings.",
    ALREADY_ACTIVE: "You already have an active request or borrowing for this book",
    SUBMIT_SUCCESS: "Borrow request submitted",
    SUBMIT_ERROR: "Failed to request book",
    FETCH_ERROR: "Failed to fetch borrowings",
    FETCH_BOOK_ERROR: "Failed to fetch borrowings for book",
    NOT_FOUND: "Request not found",
    ONLY_PENDING_ACCEPT: "Only pending requests can be accepted",
    NO_COPIES_ACCEPT: "No copies available to accept this request",
    ACCEPT_SUCCESS: "Request accepted. Book reserved for 24 hours.",
    ACCEPT_ERROR: "Failed to accept request",
    ONLY_PENDING_REJECT: "Only pending requests can be rejected",
    REJECT_SUCCESS: "Request rejected.",
    REJECT_ERROR: "Failed to reject request",
    ONLY_ACCEPTED_ISSUE: "Only accepted requests can be issued",
    ISSUE_SUCCESS: "Book issued.",
    ISSUE_ERROR: "Failed to issue book",
    ONLY_ISSUED_RETURN: "Cannot return a book that is",
    RETURN_SUCCESS: "Book returned.",
    RETURN_ERROR: "Failed to return book",
    NOT_YOURS: "Borrowing record not found or does not belong to you.",
    ONLY_PENDING_CANCEL: "Cannot cancel a request that is already",
    CANCEL_SUCCESS: "Request cancelled successfully",
    CANCEL_ERROR: "Failed to cancel request",
};

export const REVIEW_MESSAGES = {
    NOT_BORROWED: "You can only review books you have borrowed.",
    REVIEW_EXISTS: "You have already reviewed this book.",
    ADD_SUCCESS: "Review added successfully.",
    ADD_ERROR: "Failed to add review.",
    FETCH_ERROR: "Failed to fetch reviews.",
    NOT_FOUND: "Review not found.",
    DELETE_SUCCESS: "Review deleted successfully.",
    DELETE_ERROR: "Failed to delete review.",
    UNAUTHORIZED: "You are not authorized to perform this action.",
};
